- name: Install apache2 shibboleth module
  become: yes
  apt: name=libapache2-mod-shib2
       state=installed

- name: Enable apache2 shibboleth modul
  become: yes
  command: a2enmod shib2
  notify: Restart apache2

# Configure Shiboleth SP
# Create self-signed SSL certs
- name: create self-signed SSL cert
  become: yes
  command: openssl req -new -nodes -x509 -subj "/C=HU/ST=Budapest/L=Budapest/O=IT/CN=project.local" -days 3650 -keyout /etc/shibboleth/project.shibboleth.key -out /etc/shibboleth/project.shibboleth.crt
  notify: Restart shibd

# - name: Ensures /etc/shibboleth/metadata dir exists
#   file: path=/etc/shibboleth/metadata state=directory

# - name: Setup metadata.xml
#   become: yes
#   template: dest=/etc/shibboleth/metadata/metadata.xml
#             src=metadata.xml.j2
#   notify: Restart shibd

- name: Set DEBUG loglevel
  become: yes
  replace:
      #path:    /etc/shibboleth/shibd.logger
      dest:    /etc/shibboleth/shibd.logger
      regexp:  'log4j.rootCategory=INFO'
      replace: 'log4j.rootCategory=DEBUG'
  notify: Restart shibd

- name: Setup shibboleth2.xml
  become: yes
  template: dest=/etc/shibboleth/shibboleth2.xml
            src=shibboleth2.xml.j2
  notify: Restart shibd

- name: Copy attribute-map.xml
  become: yes
  copy:
    src: attribute-map.xml
    dest: /etc/shibboleth/attribute-map.xml
  notify: Restart shibd
