---
- name: Download Composer installer.
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755

- name: Run Composer installer.
  command: >
    php composer-installer.php
    chdir=/tmp
    creates=/usr/local/bin/composer

- name: Move Composer into globally-accessible location.
  shell: >
    mv /tmp/composer.phar {{ composer_path }}
    creates={{ composer_path }}

- name: Update Composer to latest version (if configured).
  shell: >
    php {{ composer_path }} self-update
  register: composer_update
  changed_when: "'Updating to version' in composer_update.stdout"
  when: composer_keep_updated

- name: Ensure composer directory exists.
  file:
    path: "{{ composer_home_path }}"
    state: directory

- name: Add GitHub OAuth token for Composer (if configured).
  template:
    src: "auth.json.j2"
    dest: "{{ composer_home_path }}/auth.json"
  when: composer_github_oauth_token != ''

- include: global-require.yml
  when: composer_global_packages|length > 0
